{%- for svc in service -%}
---
apiVersion: v1
kind: Service
metadata:
 name: name
 namespace: namespace
spec:
 type: NodePort
 ports:
 - port: {{ svc['port'] }}
   targetPort: {{ svc['port'] }}
   protocol: TCP
   name: {{svc['name']}}
 selector:
  'app': 'myapp'
{% endfor %}

